name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Executar testes
        run: mvn test

      - name: Construir o JAR
        run: mvn package -DskipTests

      - name: Armazenar artefato gerado
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
